
TP1: circulo.cpp fotometriaEstereo.cpp imagen.cpp manejadorImagenes.cpp MatrizEsparsa.cpp ppmloader.cpp TP1.cpp vector.cpp
	g++ -std=c++11 circulo.cpp fotometriaEstereo.cpp imagen.cpp manejadorImagenes.cpp MatrizEsparsa.cpp ppmloader.cpp TP1.cpp vector.cpp -o TP1

